image: mcr.microsoft.com/dotnet/sdk:5.0

variables:
  OBJECTS_DIRECTORY: 'obj'
  PACKAGES_DIRECTORY: 'packages'
  SOURCE_CODE_PATH: '*/'

stages:
  - build
  - test

cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/project.assets.json'
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/*.csproj.nuget.*'
    - '$PACKAGES_DIRECTORY'
  policy: pull-push

before_script:
  - 'dotnet restore --packages $PACKAGES_DIRECTORY'

build:
  stage: build
  script:
    - 'dotnet build --no-restore'

tests:
  stage: test
  script:
    - 'dotnet test --no-restore'
