default:
  tags:
    - windows

variables:
  OBJECTS_DIRECTORY: 'obj'
  PACKAGES_DIRECTORY: 'packages'
  SOURCE_CODE_PATH: '*/'
  DEPLOY_FOLDER: 'C:\DryerController\Server'
  SERVICE_NAME: 'DryerServer'
  GIT_CLEAN_FLAGS: -f --exclude=packages/

stages:
  - test
  - build
  - deploy

cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/project.assets.json'
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/*.csproj.nuget.*'
    - '$PACKAGES_DIRECTORY'
  policy: pull-push

before_script:
  - 'dotnet restore --packages $PACKAGES_DIRECTORY'

tests:
  stage: test
  script:
    - 'dotnet test --no-restore'

build:
  stage: build
  script:
    - 'dotnet build --no-restore -c Release -o bin'
  artifacts:
    paths:
      - bin

deploy:
  stage: deploy
  script:
    - Stop-Service -name "$env:SERVICE_NAME"
    - 'Get-ChildItem -Path  "$env:DEPLOY_FOLDER" -Recurse -exclude *.db | Remove-Item -force'
    - 'xcopy /y ".\bin" "$env:DEPLOY_FOLDER"'
    - Start-Service -name "$env:SERVICE_NAME"
  environment:
    name: production
  when: manual
  dependencies:
    - build
