// <auto-generated />
using System;
using Dryer_Server.Persistance.Model.AutoControl;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dryer_Sqlite_Persistance.Migrations.AutoControl
{
    [DbContext(typeof(AutoControlContext))]
    [Migration("20220421162825_MIGRATION_NAME")]
    partial class MIGRATION_NAME
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Dryer_Server.Persistance.Model.AutoControl.DbAutoControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ControlDifference")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ControlType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Ki")
                        .HasColumnType("REAL");

                    b.Property<float>("Kp")
                        .HasColumnType("REAL");

                    b.Property<int>("MaxInFlow")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxOutFlow")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinInFlow")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinOutFlow")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Offset")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Percent")
                        .HasColumnType("REAL");

                    b.Property<float>("TemperatureDifference")
                        .HasColumnType("REAL");

                    b.Property<TimeSpan>("TimeToSet")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Definitions");
                });

            modelBuilder.Entity("Dryer_Server.Persistance.Model.AutoControl.DbAutoControlItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InFlow")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutFlow")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<int>("ThroughFlow")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DefinitionId", "Time")
                        .IsUnique();

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("Dryer_Server.Persistance.Model.AutoControl.DbAutoControlState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AutoControlId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChamberId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AutoControlId");

                    b.ToTable("AutoControlStates");
                });

            modelBuilder.Entity("Dryer_Server.Persistance.Model.AutoControl.DbAutoControlItem", b =>
                {
                    b.HasOne("Dryer_Server.Persistance.Model.AutoControl.DbAutoControl", "Definition")
                        .WithMany("Sets")
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Definition");
                });

            modelBuilder.Entity("Dryer_Server.Persistance.Model.AutoControl.DbAutoControlState", b =>
                {
                    b.HasOne("Dryer_Server.Persistance.Model.AutoControl.DbAutoControl", "AutoControl")
                        .WithMany()
                        .HasForeignKey("AutoControlId");

                    b.Navigation("AutoControl");
                });

            modelBuilder.Entity("Dryer_Server.Persistance.Model.AutoControl.DbAutoControl", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
