// <auto-generated />
using System;
using Dryer_Server.Persistance.Model.Historical;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dryer_Sqlite_Persistance.Migrations.Historical
{
    [DbContext(typeof(HistoricalContext))]
    [Migration("20210223143351_StateTypeChanged")]
    partial class StateTypeChanged
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Dryer_Server.Persistance.Model.Historical.ChamberConvertedState", b =>
                {
                    b.Property<int>("ChamberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InFlowPosition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InFlowSet")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAuto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutFlowPosition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutFlowSet")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QueuePosition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThroughFlowPosition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThroughFlowSet")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Working")
                        .HasColumnType("INTEGER");

                    b.HasIndex("ChamberId", "TimestampUtc")
                        .IsUnique();

                    b.ToTable("State");
                });

            modelBuilder.Entity("Dryer_Server.Persistance.Model.Historical.ChamberSensorValue", b =>
                {
                    b.Property<int>("ChamberId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Humidity")
                        .HasColumnType("REAL");

                    b.Property<float>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasIndex("ChamberId", "TimestampUtc")
                        .IsUnique();

                    b.ToTable("Sensor");
                });
#pragma warning restore 612, 618
        }
    }
}
