// <auto-generated />
using System;
using Dryer_Server.Persistance.Model.Historical;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dryer_Sqlite_Persistance.Migrations.Historical
{
    [DbContext(typeof(HistoricalContext))]
    partial class HistoricalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Dryer_Server.Persistance.Model.Historical.ChamberControllerState", b =>
                {
                    b.Property<int>("ActualActuator")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChamberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Current1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Current2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Current3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Current4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Setted1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Setted2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Setted3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Setted4")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("workingStatus")
                        .HasColumnType("INTEGER");

                    b.HasIndex("ChamberId", "TimestampUtc")
                        .IsUnique();

                    b.ToTable("State");
                });

            modelBuilder.Entity("Dryer_Server.Persistance.Model.Historical.ChamberSensorValue", b =>
                {
                    b.Property<int>("ChamberId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Humidity")
                        .HasColumnType("REAL");

                    b.Property<float>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasIndex("ChamberId", "TimestampUtc")
                        .IsUnique();

                    b.ToTable("Sensor");
                });
#pragma warning restore 612, 618
        }
    }
}
